dataHW/Controllers/DictionaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace dataHW.Controllers
{
    public class DictionaryController : Controller
    {
        static Dictionary<string, int> myDictionary = new Dictionary<string, int>();

        // GET: Dictionary
        public ActionResult Index()
        {
            ViewBag.MyDictionary = myDictionary;
            return View();
        }

        //Add One item to dictionary and update viewbag
        public ActionResult AddOne()
        {
            myDictionary.Add(("New Entry " + (myDictionary.Count + 1)), (myDictionary.Count + 1));
            return View("Index");
        }

        //Add huge list of items to dictionary and update viewbag
        public ActionResult AddList()
        {
            //clear dictionary
            myDictionary.Clear();

            //add items
            for (int iCount = 0; iCount < 2000; iCount++)
            {
                myDictionary.Add("New Entry " + (myDictionary.Count + 1), (myDictionary.Count + 1));
            }

            return View("Index");
        
        }

        //Display dictionary
        public ActionResult Display()
        {
            //if Dictionary is empty, tell user
            if (myDictionary.Count == 0)
            {
                ViewBag.MyDictionary = "No items in Dictionary";
            }
            
            //load ViewBag with dictionary
            else
            {
                foreach (var item in myDictionary)
                {
                    ViewBag.MyDictionary = ViewBag.MyDictionary + item;
                }
            }

            return View("Index");
        }

        //Delete an item from Dictionary
        public ActionResult Delete()
        {
            //if Dictionary is empty, tell user
            if (myDictionary.Count == 0)
            {
                ViewBag.MyDictionary = "No items in Dictionary";
            }

            //delete item
            else
            {
                myDictionary.Remove(myDictionary.Keys.Last());
            }

            return View("Index");
        }

        //clear contents
        public ActionResult Clear()
        {
            myDictionary.Clear();
            return View("Index");
        }

        //search dictionary
        public ActionResult Search()
        {
            foreach(var item in myDictionary.Values)
            {
                if(item == 4)
                {
                    ViewBag.MyDictionary = "Item found";
                }
                else
                {
                    ViewBag.MyDictionary = "No Item found";
                }
            }

            return View("Index");
        }
    }
}

dataHW/Views/Dictionary/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <title>Dictionary Index</title>
</head>
<body>
    
    <!--Dictionary list-->
    <div class="w3-bar-block w3-black">
        <a href="@Url.Action("AddOne", "Dictionary")" class="w3-bar-item w3-button">Add one Item to Dictionary</a>
        <a href="@Url.Action("AddList", "Dictionary")" class="w3-bar-item w3-button">Add Huge List of Items to Dictionary</a>
        <a href="@Url.Action("Display", "Dictionary")" class="w3-bar-item w3-button">Display Dictionary</a>
        <a href="@Url.Action("Delete", "Dictionary")" class="w3-bar-item w3-button">Delete from Dictionary</a>
        <a href="@Url.Action("Clear", "Dictionary")" class="w3-bar-item w3-button">Clear Dictionary</a>
        <a href="@Url.Action("Search", "Dictionary")" class="w3-bar-item w3-button">Search Dictionary</a>
        <a href="@Url.Action("MainMenu", "Dictionary")" class="w3-bar-item w3-button">Return to Main Menu</a>
    </div>

    <!--Display viewbag-->
    @if (ViewBag.MyDictionary != null)
    {
        foreach (var sData in ViewBag.MyDictionary)
        {
            @sData
        }
    }

</body>
</html>